jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}

server:
  port: 8083

spring:
  datasource:
    url: ${URL}
    username: ${DB_USER}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      hobbyClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

info:
  app:
    name: goal-service
    description: Service for goals
    version: 1.0.0